version: "3"

networks:
  frontend:
  backend:

services:
  database:
    image: "postgres:latest"
    container_name: "focusify-database"
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_USER=hibernate
      - POSTGRES_PASSWORD=hibernate
      - POSTGRES_DB=hibernate_db