global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# tag::adocPrometheus[]
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]
  - job_name: 'focusify'
    metrics_path: /q/metrics
    static_configs:
      - targets: [ 'docker.for.mac.host.internal:8081' ]