version: "3.2"

networks:
  frontend:
  backend:

services:
  database:
    image: "postgres:latest"
    container_name: "focusify-database"
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_USER=hibernate
      - POSTGRES_PASSWORD=hibernate
      - POSTGRES_DB=hibernate_db

  security:
    image: "quay.io/keycloak/keycloak:15.0.2"
    container_name: "focusify-security"
    ports:
      - "8180:8080"
      - "8543:8443"
    networks:
      - backend
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  monitoring:
    image: "prom/prometheus"
    container_name: "focusify-monitoring"
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - frontend
      - backend