version: "3"

networks:
  frontend:
  backend:

services:
  database:
    image: "postgres:latest"
    container_name: "focusify-database"
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_USER=hibernate
      - POSTGRES_PASSWORD=hibernate
      - POSTGRES_DB=hibernate_db

  monitoring:
    image: "prom/prometheus"
    container_name: "focusify-monitoring"
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - frontend
      - backend

  application:
    image: "cloudbug/focusify"
    container_name: "focusify-app"
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - PORT=8080
      - QUARKUS_POSTGRES_DATABASE_URL=jdbc:postgresql://ec2-54-217-195-234.eu-west-1.compute.amazonaws.com/d71lidh085lsc6
      - DATABASE_USERNAME=carwcexuzbkziu
      - DATABASE_PASSWORD=804775df812d0513a542145bf5b5d891872406db6f264aeb7b12a32c295d103f