name: Master CICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build native application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build native with Maven
      env:
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
      run: mvn -B package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.container-image.group=registry.heroku.com/$HEROKU_APP -Dquarkus.container-image.name=focusify-web -Dquarkus.container-image.tag=latest
    - name: Upload target for next job
      uses: actions/upload-artifact@v2
      with:
        name: focusify-application
        path: focusify-application/target

  deploy_to_heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Download target from previous job
      uses: actions/download-artifact@v1
      with:
        name: focusify-application
    - name: Login into Heroku
      uses: actions/heroku@master
      with:
        args: container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Login with Docker
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - name: Build and Push to Heroku Registry
      run: docker push registry.heroku.com/$HEROKU_APP/focusify-web
      env:
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Trigger release in Heroku
      uses: actions/heroku@master
      with:
        args: container:release web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}

  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: [build, deploy_to_heroku]
    steps:
    - uses: actions/checkout@v2
    - uses: matt-ball/newman-action@master
      with:
        collection: integrationtest/TodoResource.postman_collection.json
        environment: integrationtest/env/heroku-dev.postman_environment.json
